import 'package:flutter/material.dart';

class CustomColorScheme extends ColorScheme {
  final Color warning;
  final Color info;
  final Color success;

  const CustomColorScheme({
    required super.brightness,
    required super.primary,
    required super.onPrimary,
    super.primaryContainer,
    super.onPrimaryContainer,
    super.primaryFixed,
    super.primaryFixedDim,
    super.onPrimaryFixed,
    super.onPrimaryFixedVariant,
    required super.secondary,
    required super.onSecondary,
    super.secondaryContainer,
    super.onSecondaryContainer,
    super.secondaryFixed,
    super.secondaryFixedDim,
    super.onSecondaryFixed,
    super.onSecondaryFixedVariant,
    super.tertiary,
    super.onTertiary,
    super.tertiaryContainer,
    super.onTertiaryContainer,
    super.tertiaryFixed,
    super.tertiaryFixedDim,
    super.onTertiaryFixed,
    super.onTertiaryFixedVariant,
    required super.error,
    required super.onError,
    super.errorContainer,
    super.onErrorContainer,
    required super.surface,
    required super.onSurface,
    super.surfaceDim,
    super.surfaceBright,
    super.surfaceContainerLowest,
    super.surfaceContainerLow,
    super.surfaceContainer,
    super.surfaceContainerHigh,
    super.surfaceContainerHighest,
    super.onSurfaceVariant,
    super.outline,
    super.outlineVariant,
    super.shadow,
    super.scrim,
    super.inverseSurface,
    super.onInverseSurface,
    super.inversePrimary,
    super.surfaceTint,
    required this.warning,
    required this.info,
    required this.success,
  });
}
