arb-dir: lib/l10n
output-dir: generated
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.json
format: true
use-named-parameters: true
class-name: S